### ISSUE TITLE
Profiler serialization error

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/dsbox-primitives#13]
See output: 
`/data_hdd/jun/output/docker-2020-01-30/seed/LL1_336_MS_Geolife_transport_mode_prediction_MIN_METADATA/out.txt`

```
Traceback (most recent call last):
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/JobManager/cache.py", line 222, in push_key
    self.storage[(prim_name, prim_hash)] = (fitting_time, model)
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 756, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/d3m/primitive_interfaces/base.py", line 745, in __getstate__
    'params': self.get_params(),
  File "/src/dsbox-primitives/dsbox/datapreprocessing/cleaner/data_profile.py", line 136, in get_params
    mapping=self._mapping)
  File "/usr/local/lib/python3.6/dist-packages/d3m/metadata/params.py", line 81, in __init__
    raise exceptions.InvalidArgumentTypeError("Value '{value}' for parameter '{name}' is not an instance of the type: {value_type}".format(value=value, name=name, value_type=value_type\))
```

**Comment by ckxz105** [comment]
fixed
